language: node_js
cache:
  yarn: true
notifications:
  email: false
node_js:
  - '7'
script:
  - npm run cjs
  - npm test
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
